# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Checkout
      uses: actions/checkout@v2.0.0
      with:
        # Repository name with owner. For example, actions/checkout
        repository: Azure/arm-ttk
        path: ttk_files
    - name: Build Number Generator
      id: buildnumber
      uses: einaregilsson/build-number@v2
      with:
        # GitHub Token to create and delete refs (GITHUB_TOKEN)
        token: ${{secrets.deploy_key}}   
    - name: Copy file
      run: |
        rm -r task/arm-ttk/testcases/
        cp -r ttk_files/arm-ttk/testcases/ task/arm-ttk/testcases/       
    - name: Replace Action
      uses: datamonsters/replace-action@v2
      with:
        # Files, comma-separated. Supposed PLACEHOLDER in them
        files: vss-extension.json
        # Comma-separated pairs PLACEHOLDER=value
        replacements: $buildnumber$=${{ steps.buildnumber.outputs.build_number }}
    - name: create package
      run: |
        npx tfx-cli extension create --manifest-globs vss-extension.json
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: files
        path: Sam-Cogan.ARMTTKExtension-1.0.${{ steps.buildnumber.outputs.build_number }}.vsix
        
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.5
      with:
        name: ARM TTK Extension 1.0.{{ steps.buildnumber.outputs.build_number }}
        files: Sam-Cogan.ARMTTKExtension-1.0.${{ steps.buildnumber.outputs.build_number }}.vsix
